create type "public"."difficulty" as enum ('very_difficult', 'difficult', 'neutral', 'easy', 'very_easy');

create type "public"."frequency" as enum ('very_often', 'often', 'sometimes', 'rarely', 'never');

create type "public"."read_long_texts" as enum ('yes', 'yes_but_difficult', 'no', 'no_too_difficult');

create type "public"."read_medium" as enum ('mostly_digital', 'mostly_print', 'both');

drop policy "Can view own user settings." on "public"."reader_settings";

drop policy "Users can create their own settings" on "public"."reader_settings";

drop policy "Users can edit their own settings" on "public"."reader_settings";

alter table "public"."reader_settings" drop constraint "reader_settings_settings_name_check";

alter table "public"."assessment_per_device" drop constraint "assessment_per_device_pkey";

drop index if exists "public"."assessment_per_device_pkey";

create table "public"."anita_button_state" (
    "user_id" uuid not null default auth.uid(),
    "settings" text,
    "created_at" timestamp with time zone not null default now(),
    "id" uuid not null default gen_random_uuid(),
    "updated_at" timestamp with time zone not null default now(),
    "settings_name" text not null
);


alter table "public"."anita_button_state" enable row level security;

create table "public"."global_settings" (
    "id" bigint generated by default as identity not null,
    "answerAdaptations" json,
    "defaultReaderSettings" json,
    "defaultA11ySettings" json
);


alter table "public"."global_settings" enable row level security;

alter table "public"."assessment_per_device" alter column "user_id" set not null;

alter table "public"."assessment_per_user" add column "astigmatism" boolean;

alter table "public"."assessment_per_user" add column "cognitiveLoad" frequency;

alter table "public"."assessment_per_user" add column "disoriented" frequency;

alter table "public"."assessment_per_user" add column "leftRight" frequency;

alter table "public"."assessment_per_user" add column "longTexts" read_long_texts;

alter table "public"."assessment_per_user" add column "phoneDistraction" frequency;

alter table "public"."assessment_per_user" add column "readAgain" frequency;

alter table "public"."assessment_per_user" add column "readAloud" difficulty;

alter table "public"."assessment_per_user" add column "readMedium" read_medium;

alter table "public"."assessment_per_user" add column "readingAid" boolean;

alter table "public"."assessment_per_user" add column "syllableSplitting" difficulty;

alter table "public"."assessment_per_user" add column "wordMixup" frequency;

alter table "public"."reader_settings" alter column "settings" set data type text using "settings"::text;

alter table "public"."reader_settings" alter column "settings_name" set not null;

alter table "public"."reader_settings" alter column "user_id" set default auth.uid();

alter table "public"."users" add column "birthday" date;

CREATE UNIQUE INDEX anita_button_state_pkey ON public.anita_button_state USING btree (id);

CREATE UNIQUE INDEX anita_button_state_settings_name_key ON public.anita_button_state USING btree (settings_name);

CREATE UNIQUE INDEX assessment_per_user_user_id_key ON public.assessment_per_user USING btree (user_id);

CREATE UNIQUE INDEX global_settings_pkey ON public.global_settings USING btree (id);

CREATE UNIQUE INDEX reader_settings_settings_name_key ON public.reader_settings USING btree (settings_name);

CREATE UNIQUE INDEX unique_user_ua ON public.assessment_per_device USING btree (user_id, ua);

CREATE UNIQUE INDEX assessment_per_device_pkey ON public.assessment_per_device USING btree (id);

alter table "public"."anita_button_state" add constraint "anita_button_state_pkey" PRIMARY KEY using index "anita_button_state_pkey";

alter table "public"."global_settings" add constraint "global_settings_pkey" PRIMARY KEY using index "global_settings_pkey";

alter table "public"."assessment_per_device" add constraint "assessment_per_device_pkey" PRIMARY KEY using index "assessment_per_device_pkey";

alter table "public"."anita_button_state" add constraint "a11y_settings_settings_name_check" CHECK ((length(settings_name) < 2000)) not valid;

alter table "public"."anita_button_state" validate constraint "a11y_settings_settings_name_check";

alter table "public"."anita_button_state" add constraint "anita_button_state_settings_name_key" UNIQUE using index "anita_button_state_settings_name_key";

alter table "public"."anita_button_state" add constraint "public_anita_button_state_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."anita_button_state" validate constraint "public_anita_button_state_user_id_fkey";

alter table "public"."assessment_per_device" add constraint "unique_user_ua" UNIQUE using index "unique_user_ua";

alter table "public"."assessment_per_user" add constraint "assessment_per_user_user_id_key" UNIQUE using index "assessment_per_user_user_id_key";

alter table "public"."reader_settings" add constraint "a11y_settings_settings_name_check" CHECK ((length(settings_name) < 2000)) not valid;

alter table "public"."reader_settings" validate constraint "a11y_settings_settings_name_check";

alter table "public"."reader_settings" add constraint "reader_settings_settings_name_key" UNIQUE using index "reader_settings_settings_name_key";

grant delete on table "public"."anita_button_state" to "anon";

grant insert on table "public"."anita_button_state" to "anon";

grant references on table "public"."anita_button_state" to "anon";

grant select on table "public"."anita_button_state" to "anon";

grant trigger on table "public"."anita_button_state" to "anon";

grant truncate on table "public"."anita_button_state" to "anon";

grant update on table "public"."anita_button_state" to "anon";

grant delete on table "public"."anita_button_state" to "authenticated";

grant insert on table "public"."anita_button_state" to "authenticated";

grant references on table "public"."anita_button_state" to "authenticated";

grant select on table "public"."anita_button_state" to "authenticated";

grant trigger on table "public"."anita_button_state" to "authenticated";

grant truncate on table "public"."anita_button_state" to "authenticated";

grant update on table "public"."anita_button_state" to "authenticated";

grant delete on table "public"."anita_button_state" to "service_role";

grant insert on table "public"."anita_button_state" to "service_role";

grant references on table "public"."anita_button_state" to "service_role";

grant select on table "public"."anita_button_state" to "service_role";

grant trigger on table "public"."anita_button_state" to "service_role";

grant truncate on table "public"."anita_button_state" to "service_role";

grant update on table "public"."anita_button_state" to "service_role";

grant delete on table "public"."global_settings" to "anon";

grant insert on table "public"."global_settings" to "anon";

grant references on table "public"."global_settings" to "anon";

grant select on table "public"."global_settings" to "anon";

grant trigger on table "public"."global_settings" to "anon";

grant truncate on table "public"."global_settings" to "anon";

grant update on table "public"."global_settings" to "anon";

grant delete on table "public"."global_settings" to "authenticated";

grant insert on table "public"."global_settings" to "authenticated";

grant references on table "public"."global_settings" to "authenticated";

grant select on table "public"."global_settings" to "authenticated";

grant trigger on table "public"."global_settings" to "authenticated";

grant truncate on table "public"."global_settings" to "authenticated";

grant update on table "public"."global_settings" to "authenticated";

grant delete on table "public"."global_settings" to "service_role";

grant insert on table "public"."global_settings" to "service_role";

grant references on table "public"."global_settings" to "service_role";

grant select on table "public"."global_settings" to "service_role";

grant trigger on table "public"."global_settings" to "service_role";

grant truncate on table "public"."global_settings" to "service_role";

grant update on table "public"."global_settings" to "service_role";

create policy "Can do everything on their own data"
on "public"."anita_button_state"
as permissive
for all
to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));


create policy "Enable read access for all users"
on "public"."global_settings"
as permissive
for select
to public
using (true);


create policy "Can do everything on their own data"
on "public"."reader_settings"
as permissive
for all
to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));




